### ISSUE TITLE
own data

### ISSUE THREAD

**Issue by xxbean** [MingjieChen/DYGANVC#6]
hi thanks fot the codes ! 
i just want to add my own datasets, and could you please tell me how i can do that?
thanks :)

**Comment by MingjieChen** [comment]
Hello, 

Since I don't have information about your dataset, so I can only give some points you need to consider

1. Vocoder I used is specifically for VCC2020 dataset, you may need to use a new vocoder
2. Mel-spectrogram features should have the same hop size as VQ-Wav2vec, which is 10ms.
3. For extracting speaker embeddings, you need to set your own sampling rate, which is hard-coded in my code.

If you have more questions, please let me know

**Comment by csdY123** [comment]
非常感谢你的代码。
请问运行vqw2v_feat_extract.sh时出现KeyError:'binary_请问运行vqw2v_feat_extract.sh时出现KeyError:'binary_cross_entropy'是什么原因？cross_entropy'是什么原因？

**Comment by MingjieChen** [comment]
Please have a look at this https://github.com/pytorch/fairseq/issues/3613


> 非常感谢你的代码。 请问运行vqw2v_feat_extract.sh时出现KeyError:'binary_请问运行vqw2v_feat_extract.sh时出现KeyError:'binary_cross_entropy'是什么原因？cross_entropy'是什么原因？

**Comment by csdY123** [comment]
> 请看一下这个[pytorch/fairseq#3613](https://github.com/pytorch/fairseq/issues/3613)
> 
> > 非常感谢你的代码。请运行vqw2v_feat_extract.sh时出现KeyError:'binary_请运行vqw2v_feat_extract.sh时出现KeyError:'binary_cross_entropy'是什么原因？cross_entropy'是什么原因？

谢谢，问题已经解决，但你给的网址不能解决问题，解决问题可以参考https://github.com/pytorch/fairseq/issues/3256
